# Generated by Django 2.1.1 on 2018-09-06 23:06

from django.db import migrations, models
import django.db.models.deletion
import translation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStoryPlanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NPCDialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc_name', models.CharField(max_length=100)),
                ('dialogue_file', models.FileField(upload_to=translation.models.dialogue_file_upload)),
                ('parent_planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='translation.ClassStoryPlanet')),
            ],
        ),
        migrations.AddField(
            model_name='classstoryplanet',
            name='parent_game_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='translation.GameClass'),
        ),
    ]
