# Generated by Django 2.1.1 on 2018-09-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classstoryplanet',
            old_name='name',
            new_name='ru_name',
        ),
        migrations.RenameField(
            model_name='gameclass',
            old_name='name',
            new_name='ru_name',
        ),
        migrations.AddField(
            model_name='classstoryplanet',
            name='en_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameclass',
            name='en_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
