# Generated by Django 2.1.1 on 2018-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20180907_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstoryplanet',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameclass',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
