# Generated by Django 2.1.5 on 2019-01-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=300)),
                ('url_ending', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url_ending', models.CharField(max_length=300)),
                ('parent_categories', models.ManyToManyField(blank=True, related_name='subcategories', to='video.VideoCategory')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('translation_commentaries', models.TextField(blank=True, null=True)),
                ('image_url_ending', models.CharField(max_length=300)),
                ('categories', models.ManyToManyField(blank=True, related_name='videos', to='video.VideoCategory')),
                ('editors', models.ManyToManyField(blank=True, related_name='edited_videos', to='video.Localizator')),
                ('translators', models.ManyToManyField(blank=True, related_name='translated_videos', to='video.Localizator')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_as_track_name', models.CharField(max_length=100)),
                ('url_ending', models.CharField(max_length=1000)),
                ('parent_video_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='video.VideoContainer')),
            ],
        ),
        migrations.AddField(
            model_name='subtitle',
            name='parent_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='video.VideoContainer'),
        ),
    ]
